name: Terraform Plan and Apply

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_ROOT: terraform-code
  TF_LOG: DEBUG
  TF_LOG_PATH: terraform.log

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: true

      - name: Terraform Init
        id: init
        run: terraform -chdir=$TF_ROOT init -input=false | tee tfinit.log

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=$TF_ROOT fmt -check | tee tffmt.log

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=$TF_ROOT plan -no-color -input=false -out=tfplan | tee tfplan.log
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=$TF_ROOT apply -auto-approve | tee tfapply.log
        continue-on-error: true

      - name: Upload All Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-logs
          path: |
            tfinit.log
            tffmt.log
            tfplan.log
            tfapply.log
            terraform.log
